import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import type { ElementNode } from '../state/types'
import { generateHtmlCode, generateReactCode } from './codegen'

export async function exportStaticSite(tree: ElementNode): Promise<void> {
  const zip = new JSZip()
  zip.file('index.html', generateHtmlCode(tree))
  zip.file(
    'README.md',
    '# Arkyne Export\n\nStatic HTML site generated by Arkyne.\n\nOpen `index.html` directly in a browser.\n',
  )
  const blob = await zip.generateAsync({ type: 'blob' })
  saveAs(blob, 'arkyne-static-site.zip')
}

export async function exportReactProject(tree: ElementNode): Promise<void> {
  const zip = new JSZip()

  zip.file(
    'package.json',
    JSON.stringify(
      {
        name: 'arkyne-export',
        private: true,
        version: '0.1.0',
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
        devDependencies: { '@vitejs/plugin-react': '^4.3.3', vite: '^5.4.10' },
      },
      null,
      2,
    ) + '\n',
  )

  zip.file(
    'index.html',
    `<!doctype html>\n<html>\n  <head>\n    <meta charset="utf-8" />\n    <title>Arkyne Export</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.jsx"></script>\n  </body>\n</html>\n`,
  )

  zip.file(
    'vite.config.js',
    `import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({ plugins: [react()] })\n`,
  )

  zip.file(
    'src/main.jsx',
    `import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App.jsx'\n\nReactDOM.createRoot(document.getElementById('root')).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n)\n`,
  )

  zip.file(
    'src/App.jsx',
    `import GeneratedComponent from './GeneratedComponent.jsx'\n\nexport default function App() {\n  return <GeneratedComponent />\n}\n`,
  )

  zip.file('src/GeneratedComponent.jsx', generateReactCode(tree))

  zip.file(
    'README.md',
    '# Arkyne Export\n\nReact + Vite scaffold generated by Arkyne.\n\n```bash\nnpm install\nnpm run dev\n```\n',
  )

  const blob = await zip.generateAsync({ type: 'blob' })
  saveAs(blob, 'arkyne-react-project.zip')
}
